# -*- coding: utf-8 -*-
"""LibraryManagementSystem.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U1SrhE_zPxnVYv5QIr8VbC6k6N6U-43S
"""

class Library:
  def __init__(self, file_name ="books.txt"):
    self.file_name = file_name
    self.file = open(self.file_name, "a+")

  def add_book(self):
    book_name = input("Enter the name of the book:")
    author = input("Enter the name of the author:")
    release_date = input("Enter the release date:")
    number_of_pages = input("Enter the number of pages:")
    self.file.write(f"{book_name},{author},{release_date},{number_of_pages}\n")

  def list_books(self):
    self.file.seek(0)
    lines = self.file.read().splitlines()
    for line in lines:
      book_info = line.split(',')
      book_name = book_info[0]
      author = book_info[1]
      print(f"Book name: {book_name}, Author: {author}")

  def remove_book(self):
    book_name = input("Enter the name of book:")
    self.file.seek(0)
    lines = self.file.read().splitlines()
    updated_lines = []
    for line in lines:
      book_info = line.split(',')
      if book_info[0] != book_name:
        updated_lines.append(line)

      else:
        print(f"Book {book_name} removed successfully. ")

  def close_file(self):
    self.file.close()


def main_menu():
   lib = Library()
   while True:
     print("*** Menu ***")
     print("1) List Books")
     print("2) Add Book")
     print("3) Remove Book")
     print("4) Exit")
     choice = input("Enter your choice: ")
     if choice == "1":
      lib.list_books()
     elif choice == "2":
      lib.add_book()
     elif choice == "3":
      lib.remove_book()
     elif choice =="4":
      lib.close_file()
      print("Exiting the program...")
      exit()
     else:
      print("Invalid choice. Please try again.")


if __name__ == "__main__":
    main_menu()